#! /bin/sh
#
# Written by Erik Troan (ewt@redhat.com) 1996
#            Jakub Jelinek (jj@sunsite.mff.cuni.cz) 1996,2004
#            Tomasz K³oczko (kloczek@rudy.mif.pg.gda.pl) 1997
# minor changes by Wojtek Pilorz (wpilorz@bdk.lublin.pl) 1997
# minor changes by Michele Marziani (marziani@fe.infn.it) 1997
# bug files by Marc Merlin (marcsoft@merlins.org) 1998
# locale bugfix by Michal Svec (rebel@penguin.cz) 2000
# Whitespace(s) & single quote(s) in filename workaround
#   by Andrew V. Samoilov <sav@bcs.zp.ua> 2004
# https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=64007
# patch for listing files with correct file size by Tanmoy Bhattacharya (tanmoy@mindspring.com) 2007
# minor changes by Ralf Hoffmann (ralf@boomerangsworld.de) 2007
#
# (C) 1996-2004 The Free Software Foundation.
#

# override any locale for dates
unset LC_ALL
LC_TIME=C
export LC_TIME

if rpm --nosignature --version >/dev/null 2>&1; then
  RPM="rpm --nosignature"
else
  RPM="rpm"
fi
RPM2CPIO="rpm2cpio"
SED="sed"
# Surround the whole filename with single quotes and handle specially
# \', ' and \ at the end of the string.
SEDCMD="s/\\(\\\\\\?\\)'/'\\1\\1\\\\''/g;s/\\\\\$/'\\\\\\\\'/;s/^/'/;s/\$/'/"

mcrpmfs_list ()
{
    # set MCFASTRPM_DFLT to 1 for faster rpm files handling by default, to 0 for
    # slower handling
    MCFASTRPM_DFLT=0
    if test -z "$MCFASTRPM"; then
      MCFASTRPM=$MCFASTRPM_DFLT
    fi
    f="`echo "$1" | $SED "$SEDCMD"`"
    FILEPREF="-r--r--r--   1 root     root    "
    DESC=`$RPM -qip "$f" 2>/dev/null` || {
	echo "$FILEPREF 0 "`date +"%b %d %H:%M"`" ERROR"
	exit 1
    }

    getsize() {
        $RPM -qp --qf "$1" "$f" | wc -c
    }

    writewithsize() {
        tempvar="%{$3`echo "$1" | sed -e "s/-/}-%{/g"`}\n"
        size="`getsize "$tempvar"`"
        echo "$FILEPREF $size $DATE $2/$1"
    }
    
    DATE=`$RPM -qp --qf "%{BUILDTIME:date}\n" "$f" | cut -c 5-11,21-24`
    HEADERSIZE=`echo "$DESC" | wc -c`
    echo "-r--r--r--   1 root     root  $HEADERSIZE $DATE HEADER"
    echo "-r-xr-xr-x   1 root     root    39 $DATE INSTALL"
    echo "-r-xr-xr-x   1 root     root    39 $DATE UPGRADE"
    echo "dr-xr-xr-x   3 root     root	   0 $DATE INFO"
    writewithsize NAME-VERSION-RELEASE INFO
    writewithsize GROUP INFO
    writewithsize BUILDHOST INFO
    writewithsize SOURCERPM INFO
    if test "$MCFASTRPM" = 0 ; then
        test "`$RPM -qp --qf \"%{DISTRIBUTION}\" \"$f\"`" = "(none)" ||
        writewithsize DISTRIBUTION INFO
        test "`$RPM -qp --qf \"%{VENDOR}\" \"$f\"`" = "(none)" ||
        writewithsize VENDOR INFO
        test "`$RPM -qp --qf \"%{DESCRIPTION}\" \"$f\"`" = "(none)" ||
        writewithsize DESCRIPTION INFO
        test "`$RPM -qp --qf \"%{SUMMARY}\" \"$f\"`" = "(none)" ||
        writewithsize SUMMARY INFO
        if test "`$RPM -qp --qf \"%{RPMTAG_PREIN}%{RPMTAG_POSTIN}%{RPMTAG_PREUN}%{RPMTAG_POSTUN}%{VERIFYSCRIPT}\" \"$f\"`" != "(none)(none)(none)(none)(none)"; then
	    echo "dr-xr-xr-x   1 root     root     0 $DATE INFO/SCRIPTS"
	    test "`$RPM -qp --qf \"%{RPMTAG_PREIN}\" \"$f\"`" = '(none)' ||
	    writewithsize PREIN INFO/SCRIPTS RPMTAG_
	    test "`$RPM -qp --qf \"%{RPMTAG_POSTIN}\" \"$f\"`" = '(none)' ||
	    writewithsize POSTIN INFO/SCRIPTS RPMTAG_
	    test "`$RPM -qp --qf \"%{RPMTAG_PREUN}\" \"$f\"`" = '(none)' ||
	    writewithsize PREUN INFO/SCRIPTS RPMTAG_
	    test "`$RPM -qp --qf \"%{RPMTAG_POSTUN}\" \"$f\"`" = '(none)' ||
	    writewithsize POSTUN INFO/SCRIPTS RPMTAG_
	    test "`$RPM -qp --qf \"%{VERIFYSCRIPT}\" \"$f\"`" = '(none)' ||
	    writewithsize VERIFYSCRIPT INFO/SCRIPTS
            size="`$RPM -qp --scripts "$f"|wc -c`"
            echo "$FILEPREF $size $DATE INFO/SCRIPTS/ALL"
        fi
    else
        writewithsize DISTRIBUTION INFO
        writewithsize VENDOR INFO
        writewithsize DESCRIPTION INFO
        writewithsize SUMMARY INFO
        echo "dr-xr-xr-x   1 root     root     0 $DATE INFO/SCRIPTS"
        writewithsize PREIN INFO/SCRIPTS RPMTAG_
        writewithsize POSTIN INFO/SCRIPTS RPMTAG_
        writewithsize PREUN INFO/SCRIPTS RPMTAG_
        writewithsize POSTUN INFO/SCRIPTS RPMTAG_
        writewithsize VERIFYSCRIPT INFO/SCRIPTS RPMTAG_
        size="`$RPM -qp --scripts "$f"|wc -c`"
        echo "$FILEPREF $size $DATE INFO/SCRIPTS/ALL"
    fi
    if test "$MCFASTRPM" = 0 ; then
        test "`$RPM -qp --qf \"%{PACKAGER}\" \"$f\"`" = "(none)" ||
	writewithsize PACKAGER INFO
        test "`$RPM -qp --qf \"%{URL}\" \"$f\"`" = "(none)" ||
	writewithsize URL INFO
        test "`$RPM -qp --qf \"%{SERIAL}\" \"$f\"`" = "(none)" ||
	writewithsize SERIAL INFO
        test "`$RPM -qp --qf \"%{COPYRIGHT}\" \"$f\"`" = "(none)" ||
	writewithsize COPYRIGHT INFO
        test "`$RPM -qp --qf \"%{LICENSE}\" \"$f\"`" = "(none)" ||
	writewithsize LICENSE INFO
    else
	writewithsize PACKAGER INFO
	writewithsize URL INFO
	writewithsize SERIAL INFO
	writewithsize COPYRIGHT INFO
	writewithsize LICENSE INFO
    fi
    size="`getsize "%{BUILDTIME:date}\n"`"
    echo "$FILEPREF $size $DATE INFO/BUILDTIME"
    writewithsize RPMVERSION INFO
    writewithsize OS INFO
    size="`getsize "%{SIZE} bytes\n"`"
    echo "$FILEPREF $size $DATE INFO/SIZE"
    if test "$MCFASTRPM" != 0 ; then
        size="`getsize "[%{REQUIRENAME} %{REQUIREFLAGS:depflags} %{REQUIREVERSION}\n]\n"`"
        $RPM -qp --qf "[%{REQUIRENAME}\n]" "$f" | grep "(none)" > /dev/null ||
	echo "$FILEPREF $size $DATE INFO/REQUIRENAME"
        size="`getsize "[%{OBSOLETENAME} %|OBSOLETEFLAGS?{%{OBSOLETEFLAGS:depflags} %{OBSOLETEVERSION}}:{}|\n]\n"`"
        $RPM -qp --qf "[%{OBSOLETES}\n]" "$f" | grep "(none)" > /dev/null ||
	echo "$FILEPREF $size $DATE INFO/OBSOLETES"
        size="`getsize "[%{PROVIDES}\n]\n"`"
        $RPM -qp --qf "[%{PROVIDES}\n]" "$f" | grep "(none)" > /dev/null ||
	echo "$FILEPREF $size $DATE INFO/PROVIDES"
        size="`getsize "[* %{CHANGELOGTIME:date} %{CHANGELOGNAME}\n%{CHANGELOGTEXT}\n\n]\n"`"
        test "`$RPM -qp --qf \"%{CHANGELOGTEXT}\" \"$f\"`" = "(none)" ||
        echo "$FILEPREF $size $DATE INFO/CHANGELOG"
    else 
	size="`getsize "[%{REQUIRENAME} %{REQUIREFLAGS:depflags} %{REQUIREVERSION}\n]\n"`"
	echo "$FILEPREF $size $DATE INFO/REQUIRENAME"
	size="`getsize "[%{OBSOLETENAME} %|OBSOLETEFLAGS?{%{OBSOLETEFLAGS:depflags} %{OBSOLETEVERSION}}:{}|\n]\n"`"
	echo "$FILEPREF $size $DATE INFO/OBSOLETES"
	size="`getsize "[%{PROVIDES}\n]\n"`"
	echo "$FILEPREF $size $DATE INFO/PROVIDES"
	size="`getsize "[* %{CHANGELOGTIME:date} %{CHANGELOGNAME}\n%{CHANGELOGTEXT}\n\n]\n"`"
        echo "$FILEPREF $size $DATE INFO/CHANGELOG"
    fi
    size="`eval $RPM2CPIO "$f" | wc -c`"
    echo "$FILEPREF $size $DATE CONTENTS.cpio"
}

mcrpmfs_copyout ()
{
    f="`echo "$1" | $SED "$SEDCMD"`"
    case "$2" in
	HEADER) $RPM -qip "$f" > "$3"; exit 0;;
	INSTALL) echo "# Run this to install this RPM package" > "$3"; exit 0;;
	UPGRADE) echo "# Run this to upgrade this RPM package" > "$3"; exit 0;;
	ERROR) $RPM -qip "$f" > /dev/null 2> "$3"; exit 0;;
	INFO/NAME-VERSION-RELEASE)	$RPM -qp --qf "%{NAME}-%{VERSION}-%{RELEASE}\n" "$f" > "$3"; exit 0;;
	INFO/RELEASE)		$RPM -qp --qf "%{RELEASE}\n" "$f" > "$3"; exit 0;;
	INFO/GROUP)		$RPM -qp --qf "%{GROUP}\n" "$f" > "$3"; exit 0;;
	INFO/DISTRIBUTION) 	$RPM -qp --qf "%{DISTRIBUTION}\n" "$f" > "$3"; exit 0;;
	INFO/VENDOR)		$RPM -qp --qf "%{VENDOR}\n" "$f" > "$3"; exit 0;;
	INFO/BUILDHOST)		$RPM -qp --qf "%{BUILDHOST}\n" "$f" > "$3"; exit 0;;
	INFO/SOURCERPM)		$RPM -qp --qf "%{SOURCERPM}\n" "$f" > "$3"; exit 0;;
	INFO/DESCRIPTION)	$RPM -qp --qf "%{DESCRIPTION}\n" "$f" > "$3"; exit 0;;
	INFO/PACKAGER)		$RPM -qp --qf "%{PACKAGER}\n" "$f" > "$3"; exit 0;;
	INFO/URL)		$RPM -qp --qf "%{URL}\n" "$f" >"$3"; exit 0;;
	INFO/BUILDTIME)		$RPM -qp --qf "%{BUILDTIME:date}\n" "$f" >"$3"; exit 0;;
	INFO/SERIAL)		$RPM -qp --qf "%{SERIAL}\n" "$f" >"$3"; exit 0;;
	INFO/COPYRIGHT)		$RPM -qp --qf "%{COPYRIGHT}\n" "$f" >"$3"; exit 0;;
	INFO/LICENSE)		$RPM -qp --qf "%{LICENSE}\n" "$f" >"$3"; exit 0;;
	INFO/RPMVERSION)	$RPM -qp --qf "%{RPMVERSION}\n" "$f" >"$3"; exit 0;;
	INFO/REQUIRENAME)	$RPM -qp --qf "[%{REQUIRENAME} %{REQUIREFLAGS:depflags} %{REQUIREVERSION}\n]\n" "$f" >"$3"; exit 0;;
	INFO/PROVIDES)		$RPM -qp --qf "[%{PROVIDES}\n]\n" "$f" >"$3"; exit 0;;
	INFO/SCRIPTS/PREIN)	$RPM -qp --qf "%{RPMTAG_PREIN}\n" "$f" >"$3"; exit 0;;
	INFO/SCRIPTS/POSTIN)	$RPM -qp --qf "%{RPMTAG_POSTIN}\n" "$f" >"$3"; exit 0;;
	INFO/SCRIPTS/PREUN)	$RPM -qp --qf "%{RPMTAG_PREUN}\n" "$f" >"$3"; exit 0;;
	INFO/SCRIPTS/POSTUN)	$RPM -qp --qf "%{RPMTAG_POSTUN}\n" "$f" >"$3"; exit 0;;
	INFO/SCRIPTS/VERIFYSCRIPT)	$RPM -qp --qf "%{VERIFYSCRIPT}\n" "$f" >"$3"; exit 0;;
	INFO/SCRIPTS/ALL)		$RPM -qp --scripts "$f" > "$3"; exit 0;;
	INFO/SUMMARY)		$RPM -qp --qf "%{SUMMARY}\n" "$f" > "$3"; exit 0;;
	INFO/OS)		$RPM -qp --qf "%{OS}\n" "$f" > "$3"; exit 0;;
	INFO/CHANGELOG)		$RPM -qp --qf "[* %{CHANGELOGTIME:date} %{CHANGELOGNAME}\n%{CHANGELOGTEXT}\n\n]\n" "$f" > "$3"; exit 0;;
	INFO/SIZE)		$RPM -qp --qf "%{SIZE} bytes\n" "$f" > "$3"; exit 0;;
	INFO/OBSOLETES)		$RPM -qp --qf "[%{OBSOLETENAME} %|OBSOLETEFLAGS?{%{OBSOLETEFLAGS:depflags} %{OBSOLETEVERSION}}:{}|\n]\n" "$f" > "$3"; exit 0;;
	CONTENTS.cpio)		$RPM2CPIO "$1" > "$3"; exit 0;;
	*)
	    ;;
    esac
}

mcrpmfs_run ()
{
    f="`echo "$1" | $SED "$SEDCMD"`"
    case "$2" in
	INSTALL) echo "Installing \"\"$f\"\""; $RPM -ivh "$f"; exit 0;;
	UPGRADE) echo "Upgrading \"\"$f\"\""; $RPM -Uvh "$f"; exit 0;;
    esac
}

umask 077
case "$1" in
  list) mcrpmfs_list "$2"; exit 0;;
  copyout) mcrpmfs_copyout "$2" "$3" "$4"; exit 0;;
  run) mcrpmfs_run "$2" "$3"; exit 1;;
esac
exit 1
